### ISSUE TITLE
Greenworks

### ISSUE THREAD

**Issue by m5kro** [Revival8697/RPG-Maker-MV-MZ-Linux-Guide#1]
Hi, on some games there is a plugin called Greenworks that lets games communicate with the Steam API. Most games only come with the windows libraries so porting to Linux requires an extra step of adding the required files. I think it would be a good idea to mention that in the readme.

Edit:
You can find prebuilt libararies here: https://greenworks-prebuilds.armaldio.xyz/
Also look at karryn's prison if you are confused on where the files go, it has libs for linux, mac, and windows included, which is rare to see

**Comment by Revival8697** [comment]
For Steam games, I personally think they should be played though the Steam client (though Proton or native).
I create this repo to manage games from sites where you download the games as is (like DLSite).
